from typing import Any, overload

class Regex:
    # TODO: add 'global' attributes, like ASCII, UNICODE
    #  GREEDY, NOT_GREEDY, MULTILINE, etc.
    def __init__(self, regex: str, *args: list[Any]) -> None: ...
    @overload
    def __contains__(self, text: str) -> bool: ...  # whether 'text' matches regex
    @overload
    def __contains__(
        self, regex: Regex
    ) -> bool: ...  # whether one regex is a subset of another
    # str - fmatch/search - remove this method?
    # Regex - "recognizes same language"
    def __eq__(self, other: object) -> bool: ...
    @overload
    def __add__(self, other: Regex) -> Regex: ...
    @overload
    def __add__(self, other: str) -> Regex: ...
    def __radd__(self, other: str) -> Regex: ...
    @overload
    def __sub__(self, other: Regex) -> Regex: ...
    @overload
    def __sub__(self, other: str) -> Regex: ...
    def __rsub__(self, other: str) -> Regex: ...
    def __neg__(self) -> Regex: ...
    def __bool__(self) -> Regex: ...  # for the purpose of 'not' operator?
    @overload
    def __getitem__(self, item: int) -> Regex: ...  # numbered capture group
    @overload
    def __getitem__(self, item: str) -> Regex: ...  # named capture group
    def compile(self) -> None: ...
    def fmatch(self, *args: list[Any]) -> Match: ...
    def lmatch(self, *args: list[Any]) -> Match: ...
    def rmatch(self, *args: list[Any]) -> Match: ...
    def search(self, *args: list[Any]) -> Match: ...
    def empty(self) -> bool: ...  # recognizes empty language, perhaps for debugging
    def full(self) -> bool: ...
    def star(self) -> Regex: ...
    def plus(self) -> Regex: ...
    def complement(self) -> Regex: ...
    def __reversed__(self) -> Regex: ...  # language in the opposite direction
    def reversed(self) -> Regex: ...  # language in the opposite direction
    def repeat(self, min: int = None, max: int = None) -> Regex: ...  # {min,max}
    # TODO: max possible string
    # TODO: min possible string
    # TODO: number of possible strings

class Match:
    pass
