from typing import overload


class Regex:
    def __init__(self, regex: str) -> None: ...

    def __eq__(self, other: str) -> bool: ...

    @overload
    def __add__(self, other: Regex) -> Regex: ...

    @overload
    def __add__(self, other: str) -> Regex: ...

    def __radd__(self, other: str) -> Regex: ...

    @overload
    def __sub__(self, other: Regex) -> Regex: ...

    @overload
    def __sub__(self, other: str) -> Regex: ...

    def __rsub__(self, other: str) -> Regex: ...
